pub mod agent_bots;
pub mod execution_logs;
pub mod execution_records;
pub mod executors;
pub mod feishu_homes;
pub mod feishu_history_chats;
pub mod feishu_messages;
pub mod feishu_push_targets;
pub mod feishu_response_config;
pub mod feishu_group_whitelist;
pub mod global_default_hooks;
pub mod global_hook_config;
pub mod hook_logs;
pub mod hooks;
pub mod project_directories;
pub mod tags;
pub mod todo_hook_rules;
pub mod todo_hooks;
pub mod todo_tags;
pub mod todo_templates;
pub mod todos;
pub mod webhooks;
pub mod webhook_records;

pub mod prelude {
    pub use super::agent_bots::Entity as AgentBots;
    pub use super::execution_logs::Entity as ExecutionLogs;
    pub use super::execution_records::Entity as ExecutionRecords;
    pub use super::executors::Entity as Executors;
    pub use super::feishu_homes::Entity as FeishuHomes;
    pub use super::feishu_history_chats::Entity as FeishuHistoryChats;
    pub use super::feishu_messages::Entity as FeishuMessages;
    pub use super::feishu_push_targets::Entity as FeishuPushTargets;
    pub use super::feishu_response_config::Entity as FeishuResponseConfig;
    pub use super::feishu_group_whitelist::Entity as FeishuGroupWhitelist;
    pub use super::global_default_hooks::Entity as GlobalDefaultHooks;
    pub use super::global_hook_config::Entity as GlobalHookConfig;
    pub use super::hook_logs::Entity as HookLogs;
    pub use super::hooks::Entity as Hooks;
    pub use super::project_directories::Entity as ProjectDirectories;
    pub use super::tags::Entity as Tags;
    pub use super::todo_hook_rules::Entity as TodoHookRules;
    pub use super::todo_hooks::Entity as TodoHooks;
    pub use super::todo_tags::Entity as TodoTags;
    pub use super::todo_templates::Entity as TodoTemplates;
    pub use super::todos::Entity as Todos;
    pub use super::webhooks::Entity as Webhooks;
    pub use super::webhook_records::Entity as WebhookRecords;
}
